del "*.suo" /S/Q/F/A
del "*.csproj.user" /S/Q/F/A
del "pos-tagger_ru.web.demo\bin\*.pdb" /Q
rd "pos-tagger_ru.web.demo\obj" /S/Q
rd "pos-tagger_ru.web.demo\(logs)" /S/Q
rd "captcha\bin" /S/Q
rd "captcha\obj" /S/Q
rd "crfsuite.net\bin" /S/Q
rd "crfsuite.net\obj" /S/Q
rd "lingvo.core\bin" /S/Q
rd "lingvo.core\obj" /S/Q
rd "pos-tagger-crf.net\bin" /S/Q
rd "pos-tagger-crf.net\obj" /S/Q
rd "SentSplitter\bin" /S/Q
rd "SentSplitter\obj" /S/Q
rd "morphology\bin" /S/Q
rd "morphology\obj" /S/Q
